M48
; DRILL file {KiCad (6.0.0)} date Fri Jan 21 19:36:20 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-21T19:36:20+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X105.0Y-105.0
X105.0Y-145.0
X122.645Y-115.0
X178.255Y-115.0
X195.0Y-105.0
X195.0Y-145.0
T0
M30
